# Generated by Django 4.2 on 2023-10-17 15:22

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_file_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='avatar',
            field=thumbnails.fields.ImageField(blank=True, upload_to='categories/', verbose_name='avatar'),
        ),
    ]
