# Generated by Django 4.2 on 2023-10-18 08:14

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avatar',
            field=thumbnails.fields.ImageField(blank=True, upload_to='products/', verbose_name='avatar'),
        ),
    ]
