# Generated by Django 4.2 on 2023-10-19 10:55

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avatar',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='products/', verbose_name='avatar'),
        ),
    ]
