# Generated by Django 4.2 on 2023-11-05 12:28

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='avatar',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='avatar'),
        ),
    ]
