# Generated by Django 4.2 on 2023-11-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test_field',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='test field'),
        ),
    ]
