# Generated by Django 4.2 on 2023-11-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test_field',
        ),
    ]
