# Generated by Django 4.2 on 2023-11-05 09:55

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='avatar',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='gateway/', verbose_name='avatar'),
        ),
    ]
