# Generated by Django 4.2 on 2023-11-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_gateway_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='price',
        ),
    ]
