# Generated by Django 4.2 on 2023-11-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
