# Generated by Django 4.2 on 2023-09-20 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_device_device_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Device UUID'),
        ),
    ]
