# Generated by Django 4.2 on 2023-11-02 07:59

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='UserProfile/', verbose_name='avatar'),
        ),
    ]
