# Generated by Django 4.2 on 2023-11-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
