# Generated by Django 4.2 on 2023-11-06 13:08

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_province_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='User/', verbose_name='avatar'),
        ),
    ]
