# Generated by Django 4.2 on 2023-11-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(blank=True, help_text='female is False, male is True, null is unset', null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='nick_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nick name'),
        ),
    ]
