# Generated by Django 4.2 on 2023-11-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_gender_user_nick_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
