# Generated by Django 4.2 on 2023-11-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(blank=True, help_text='female is No, male is Yes, Unknown is unset', null=True, verbose_name='gender'),
        ),
    ]
